services:
  backend:
    build:
      context: back-end
      dockerfile: Dockerfile.prod
    ports:
      - 8030:8030
  frontend:
    build:
      context: front-end
      dockerfile: Dockerfile.prod
    ports:
      - 3030:3030
  worker:
    build:
      context: back-end
      dockerfile: Dockerfile.prod
    command: python3 worker.py
  mongodb:
    image: mongo:8-noble
    volumes:
      - uangkasepmongo2:/data/db
    env_file:
      - .env
    logging:
      driver: none
  redis:
    image: redis:7.4.1-alpine3.20
volumes:
  uangkasepmongo2: