FROM python:3.12-alpine3.20

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV REDIS_URL=redis://redis/0
ENV PYTHONUNBUFFERED=1

CMD granian --interface asgi main:app --host 0.0.0.0 --port 8030